### ISSUE TITLE
readme.md не хватает инфы

### ISSUE THREAD

**Issue by VikingBO** [manchenkoff/skillbox-chat#4]
При выполнении команды

`pip install pywin32`

выдало ошибку вдруг

`  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32`

на стаке нашел совет использовать для установки

`pip install pypiwin32`

попробовал, не помогло, ошибка та же самая.

**Comment by manchenkoff** [comment]
поддержку для Windows убрали с версии Python 3.4, так что убираю из readme.md, спасибо что отписались
